user:
  per_page: 10
  name_max_length: 50
  email_max_length: 255
  phone_number_max_length: 15
  min_password: 6
  address_max_length: 255
category:
  per_page: 10
  name_max_length: 255
product:
  name_max_length: 50
  description_max_length: 1000
  area_rows: 3
  per_page: 12
  image_accept: ["image/jpeg", "image/gif", "image/png"]
  size_thumb: "100x100>"
  size_medium: "300x300>"
  default_image: "image_:style"
suggest:
  per_page: 10
  area_rows: 3
  content_max_length: 255
  image_accept: ["image/jpeg", "image/gif", "image/png"]
  size_thumb: "100x100>"
  size_medium: "300x300>"
order:
  per_page: 10
  format_time: "%H:%M:%S %d/%M/%Y"
  mail_default: "ecomerce45.framgia@gmail.com"
